### Test genesis block

GET http://localhost:8000/block/height/0
Accept: application/json

### Request of ownership

POST http://localhost:8000/requestValidation
Accept: application/json
Content-Type: application/json

{
  "address": "2N8RcCnzhhD6d6CYYderqcnvKLY4vsnPwVk"
}

### Submit a Star

POST http://localhost:8000/submitstar
Accept: application/json
Content-Type: application/json

{
  "address": "n4aqru1mgMDcPeyy3qemMg4iEhkBoKzDFJ",
  "signature": "ILHfPwOrOb69p3gG9BH97EBVPLuHsuGzK2MFxYRwKF37SQYC1282rqzKJCiQ70kTzrJN8QCnCrBNFXdeQGnJByQ=",
  "message": "2N8RcCnzhhD6d6CYYderqcnvKLY4vsnPwVk:1623724573:starRegistry",
  "star": {
    "dec": "68° 52' 56.9",
    "ra": "16h 29m 1.0s",
    "story": "Testing the story 3"
  }
}

### Retrieve Stars by owner

GET http://localhost:8000/blocks/n4aqru1mgMDcPeyy3qemMg4iEhkBoKzDFJ
Accept: application/json

### Retrieve Block by Hash
GET localhost:8000/block/hash/
Accept: application/json